export type SeoSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type SeoPage = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  headline: string;
  accent: string;
  kind: "tool" | "guide" | "technical";
  sections: SeoSection[];
  faqs: { question: string; answer: string }[];
  related: string[];
};

const commonFaqs = [
  { question: "Will my PDF remain valid?", answer: "The API validates the generated PDF before returning it. Native text and vectors are preserved when the source format allows it." },
  { question: "Is my document stored?", answer: "The service processes uploads temporarily and does not use document contents for analytics. Production retention should be configured before launch." },
];
const tool = (slug: string, title: string, description: string, eyebrow: string, headline: string, accent: string, sections: SeoSection[], related: string[], faqs = commonFaqs): SeoPage => ({ slug, title, description, eyebrow, headline, accent, kind: "tool", sections, faqs, related });

export const seoPages: SeoPage[] = [
  tool("compress-pdf", "Compress PDF Online", "Reduce PDF file size with smart, content-aware compression.", "The everyday PDF compressor", "Compress PDF online", "without the guesswork.", [{ heading: "Compress your PDF in seconds", paragraphs: ["Upload a document, choose a compression level, and download the result. PDFluv inspects pages and embedded images before selecting an optimization path."], bullets: ["Scanned pages", "Photographs and embedded images", "PDF streams and unused resources", "Fonts where safe"] }, { heading: "Smart compression instead of one blunt preset", paragraphs: ["A photograph, a scanned form, and a digitally generated report have different failure modes. The compressor treats them differently so readable text does not pay the price for a large image."] }], ["reduce-pdf-size", "compress-scanned-pdf", "compress-pdf-without-losing-quality"], [{ question: "Does compressing a PDF reduce quality?", answer: "It can, depending on the mode. Balanced compression trades some image information for a smaller file while keeping the document usable." }, ...commonFaqs]),
  tool("reduce-pdf-size", "Reduce PDF File Size Online", "Make PDFs smaller while preserving readable text and important visual detail.", "When the file is too large", "Reduce PDF file size", "and keep moving.", [{ heading: "Why is my PDF so large?", paragraphs: ["Large scans, high-resolution photographs, duplicate images, uncompressed streams, embedded fonts, and color data can all add weight."], bullets: ["300 or 600 DPI scans", "Photos placed at print resolution", "Repeated logos and page resources", "Color data where grayscale would work"] }, { heading: "Choose a target that fits the job", paragraphs: ["Use 500 KB, 1 MB, 2 MB, or a custom limit when a portal, email provider, or sharing workflow gives you a ceiling. Not every source PDF can reach every target."] }], ["compress-pdf", "compress-pdf-to-1mb", "compress-pdf-for-email"], [{ question: "Why is my PDF still large after compression?", answer: "Some PDFs are already optimized or mostly contain text and vector data, leaving less removable image data." }, ...commonFaqs]),
  tool("compress-pdf-online", "Compress PDF Online Without Software", "Compress PDFs directly from your browser on desktop or mobile.", "No installation required", "Compress PDF online", "from any device.", [{ heading: "Compress PDFs from any device", paragraphs: ["The browser workflow works on Windows, Mac, Chromebook, Android, iPhone, and tablets. Choose a local PDF, process it, and save the returned file."], bullets: ["Email attachments", "Government or application portals", "College submissions", "Cloud and mobile sharing"] }, { heading: "Is online PDF compression safe?", paragraphs: ["Use HTTPS in production, enforce upload limits, isolate processing, and delete temporary files automatically. These controls belong in deployment configuration, not just marketing copy."] }], ["compress-pdf", "reduce-pdf-size-on-android", "reduce-pdf-size-on-iphone"], [{ question: "Do I need to install anything?", answer: "No desktop software is required for the browser workflow." }, ...commonFaqs]),
  tool("compress-pdf-without-losing-quality", "Compress PDF Without Losing Quality", "Reduce PDF size while keeping text readable and images clear.", "Quality is a constraint", "Compress PDF", "without losing what matters.", [{ heading: "Lossless versus visually lossless", paragraphs: ["Lossless compression removes redundant representation without discarding visual information. Lossy compression can be much smaller, but it must be judged by readability and use case rather than a promise of pixel-perfect identity."] }, { heading: "Why every page needs a different route", paragraphs: ["Text-heavy scans may benefit from monochrome optimization. Photos usually suit JPEG. Digital PDFs should keep their native text and vector content whenever possible."] }, { heading: "Quality-constrained compression", paragraphs: ["A production engine can generate candidates, measure their size and quality, then select the smallest candidate that remains above the chosen quality threshold."] }], ["compress-pdf", "compress-scanned-pdf", "compression-technology"]),
  tool("compress-scanned-pdf", "Compress Scanned PDF Online", "Reduce scanned document size with resolution-aware image optimization.", "For scans, forms and photocopies", "Compress scanned PDFs", "without flattening the details.", [{ heading: "Why scanned PDFs are large", paragraphs: ["A scanner turns each paper page into a bitmap. At 300 or 600 DPI, a multi-page document can contain dozens of large full-page images and no searchable text layer."], bullets: ["Bank statements", "Loan and property documents", "Invoices and school records", "Legal and government documents"] }, { heading: "How scan-aware compression works", paragraphs: ["The engine can detect image resolution, downsample oversized pages, and recompress the result. OCR validation should be added before claiming that an image-only scan remains searchable."] }], ["compress-pdf", "compress-pdf-to-1mb", "compression-technology"], [{ question: "Can an image-only scan become searchable?", answer: "Compression alone does not add searchable text. OCR is a separate processing step and should be explicitly enabled and validated." }, ...commonFaqs]),
];

for (const [suffix, label, angle] of [["100kb", "100KB", "Very small uploads need aggressive trade-offs."], ["200kb", "200KB", "More room for quality than a 100KB ceiling."], ["500kb", "500KB", "A practical middle ground for forms and sharing."], ["1mb", "1MB", "A common moderate target for applications and portals."], ["2mb", "2MB", "More room for visual detail in multi-page documents."]] as const) {
  seoPages.push(tool(`compress-pdf-to-${suffix}`, `Compress PDF to ${label}`, `Try to reduce a PDF to ${label} while keeping the document usable.`, `Target size: ${label}`, `Compress PDF to ${label}`, angle, [{ heading: `Can every PDF reach ${label}?`, paragraphs: [`No. A short text document may fit easily, while a high-resolution photograph or long scanned file may not. The optimizer should report when the requested ceiling is too aggressive.`] }, { heading: "How target-size compression works", paragraphs: [`The service tries progressively stronger image quality and resolution candidates, checks the resulting byte size, and returns the first candidate at or below ${label}.`] }], ["compress-pdf", "reduce-pdf-size", "compress-scanned-pdf"], [{ question: `What if my PDF cannot reach ${label}?`, answer: "The service returns an error rather than silently claiming that the target was achieved. Keep the original and choose a less aggressive target." }, ...commonFaqs]));
}

seoPages.push(
  tool("compress-pdf-for-email", "Compress PDF for Email", "Make large PDF attachments easier to send by reducing unnecessary file size.", "For sending, not shrinking blindly", "Compress PDF for email", "and check the limit first.", [{ heading: "What size should an email PDF be?", paragraphs: ["Attachment limits vary by provider, so check yours and choose a target below it. Compression is useful when the recipient needs the file itself; a cloud link may be better for very large documents."] }, { heading: "Why attachments become large", paragraphs: ["High-resolution scans, photographs, multiple pages, and embedded resources are common causes."] }], ["compress-pdf", "compress-pdf-to-1mb", "reduce-pdf-size"]),
  tool("compress-pdf-for-whatsapp", "Compress PDF for WhatsApp", "Reduce PDF size before mobile sharing while keeping the document readable.", "For mobile sharing", "Compress PDF for WhatsApp", "before you send it.", [{ heading: "Why compress before sharing?", paragraphs: ["A smaller file can upload faster, use less mobile data, and take less storage. Choose a target based on your file and current sharing constraints."] }, { heading: "Use it from your phone", paragraphs: ["Open the compressor in your mobile browser, select the PDF from Files, choose a target, compress, and save the result."] }], ["compress-pdf", "reduce-pdf-size-on-android", "reduce-pdf-size-on-iphone"]),
);
for (const device of ["android", "iphone"] as const) seoPages.push({ slug: `reduce-pdf-size-on-${device}`, title: `How to Reduce PDF Size on ${device === "iphone" ? "iPhone" : "Android"}`, description: `Reduce PDF file size from your ${device === "iphone" ? "iPhone" : "Android phone"} using a browser-based workflow.`, eyebrow: `Mobile guide: ${device === "iphone" ? "iPhone" : "Android"}`, headline: `Reduce PDF size on ${device === "iphone" ? "iPhone" : "Android"}`, accent: "without a desktop computer.", kind: "guide", sections: [{ heading: "Use the online compressor", paragraphs: ["Open the tool in your browser, select the PDF from Files, choose a compression level, select a target if needed, compress, and download the result."] }, { heading: "Keep the original until you verify", paragraphs: ["Check the new file size and open a few pages before deleting the original. When creating a new scan, crop unnecessary borders and avoid higher resolution than the document needs."] }], faqs: commonFaqs, related: ["compress-pdf-online", "compress-pdf-for-whatsapp", "compress-pdf-to-1mb"] });
seoPages.push({ slug: "compression-technology", title: "How Smart PDF Compression Works", description: "Understand page analysis, image optimization, quality measurement, and PDF validation.", eyebrow: "Technical authority", headline: "How smart PDF compression works", accent: "under the surface.", kind: "technical", sections: [{ heading: "The optimization pipeline", paragraphs: ["PDF analysis leads to page and image classification, region-aware candidate generation, quality measurement, optimization, and final PDF validation."] }, { heading: "Codec selection depends on content", paragraphs: ["JPEG suits photographs. CCITT Group 4 can suit suitable monochrome images. JBIG2 can be effective for text-heavy scans but lossy symbol substitution needs careful validation. Flate remains useful for lossless streams and graphics."] }], faqs: commonFaqs, related: ["compress-pdf", "compress-scanned-pdf", "benchmarks"] });
seoPages.push({ slug: "benchmarks", title: "PDF Compression Benchmarks", description: "Transparent PDF compression measurements with reproducible source documents.", eyebrow: "Measure, then claim", headline: "PDF compression benchmarks", accent: "with no invented numbers.", kind: "technical", sections: [{ heading: "What a useful benchmark records", paragraphs: ["A real benchmark should record original size, output size, reduction percentage, processing time, memory, quality metrics, OCR results where relevant, codec, and engine version."], bullets: ["Use representative scan, photo, mixed, and text PDFs", "Publish the source conditions", "Do not compare tools without matching settings"] }, { heading: "Current status", paragraphs: ["This route is ready for benchmark data, but performance numbers should not be published until a repeatable fixture set has been processed by the deployed engine."] }], faqs: commonFaqs, related: ["compression-technology", "compress-pdf", "compress-scanned-pdf"] });

export const siteUrl = "https://pdfluv.vercel.app";
